def gv
pipeline{
  agent any
  parameters{
    choice(name: 'VERSION', choices: ['1.1.0', '1.2.0', '1.3.0'], description: '')
    booleanParam(name: 'executeTests', defaultValue: true, description: '')
  }
  stages{
    stage('init'){
      steps{
        script{
          gv = load "maven-demo/script.groovy"
        }
      }
    }

    stage('Build'){
      steps{
        script{
          gv.buildApp()
        }
      }
    }

    stage('Test'){
      when{
        expression{
          params.executeTests
        }
      }
      steps{
        script{
          gv.testApp()
        }
      }
    }

    stage('Deploy'){
      input{
        message "Which Server do you want to deploy?"
        ok "Done"
        parameters{
          choice(name: 'SERVER', choices: ['Staging', 'Testing', 'Production'], description: '')
        }
      }
      steps{
        script{
          gv.deployApp()
          echo "Deployed to ${SERVER} Server"
        }
      }
    }
    
  }
}
